version: '3'

services:
  weaver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3838"
    volumes:
      - ./config.yml:/srv/shiny-server/weaver/config.yml
    networks: [app]

# stops docker from messing up the Openstack instance network config
networks:
  app:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.1/24
